apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: frontend
    newName: 282531899059.dkr.ecr.us-east-1.amazonaws.com/movie-frontend
    newTag: latest
